### ISSUE TITLE
dry run checklist

### ISSUE THREAD

**Issue by raprasad** [vjdorazio/TwoRavens#40]
- [ ] #38 rook application, configurable output directory for images and preprocess files 
   - could be a shared volume via kubernetes
- [ ] #33 grpc service.  (? https://pypi.python.org/pypi/skitai#implementing-grpc-service)
- [ ] #26 read/load D3m config file from shared volume.  
   - assuming we still need R preprocess.  
      - What about the 100MB+ and 3GB+ files?  May need to queue the R service response?
   - needed to write output
- [x] ~~websockets for web server to relay responses from the grpc service~~
   -~~for dry run; flask or django channels.  (does nodejs make more sense as the webapp layer?)~~ 
- [x] dockerfiles for:
   - python app
      - depending, may need sep. service for websockets; although django channels looks promising
   - r services (took)
   - grpc (likely)
- [ ] #41 All dockerfiles in gitlab
   - when do we copy this over from github
- [ ] #41 autobuild on docker hub for outside world
- [ ] #35 submit system description - TA3 system requirement
- [ ] kubernates configuration in gitlab file to run multiple services (template will come from NIST)
- [ ] openstack application running for user test (not NIST test)
   - either proxy service from data machines or log in is needed
- [ ] log file generation
